source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
inhibit_all_warnings!

platform :ios, '10.0'

target 'DStackExample' do

    pod 'DStack',
        :subspecs => ['Controllers'],
        :path => '..'
    pod 'SwiftLint'

end
