source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
inhibit_all_warnings!

platform :ios, '10.0'

target 'DStackExample' do

    pod 'DStack',
        :subspecs => ['Controllers'],
        :path => '..'
    pod 'SwiftLint'
    pod 'RxSwift', :git => 'https://github.com/ReactiveX/RxSwift.git', :tag => 'rxswift4.0-swift4.0'
    pod 'RxCocoa', '4.0.0-beta.0'

end
